services:
  - type: web
    name: gemini-stream-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      # Set these in the Render dashboard (do not commit secrets)
      # - key: GEMINI_API_KEY
      #   sync: false
      # - key: GOOGLE_GEMINI_API_KEY
      #   sync: false
      # - key: OPENAI_TTS_API_KEY
      #   sync: false
